### PR TITLE
fix: Fix Daemonset schema, update strategy placed incorrectly

### PR DESCRIPTION
**Pull request by grzesuav**

### CODE REVIEW

**Comment by sphr2k** [comment]
~~ich ~~

**Comment by apetruhin** [comment]
@grzesuav,  could you please set the default value of `maxUnavailable: 1` in values.yaml?

**Comment by grzesuav** [comment]
> @grzesuav,  could you please set the default value of `maxUnavailable: 1` in values.yaml?

I can if it is desired but it will be impractical on medium/large clusters

**Comment by apetruhin** [comment]
> > @grzesuav,  could you please set the default value of `maxUnavailable: 1` in values.yaml?
> 
> I can if it is desired but it will be impractical on medium/large clusters

You can override it if you need a faster rollout for some reason.

**Comment by grzesuav** [comment]
@apetruhin done

**Pull request merged**
