### PR TITLE
fix mount crio sock

### PR DESCRIPTION
**Pull request by anngdinh**
Node agent need mount crio sock

### CODE REVIEW

**Comment by def** [comment]
It's not necessary to mount this because the agent can access the host filesystem

**Comment by anngdinh** [comment]
I got this error if not mount

image

**Comment by def** [comment]
Please show the beginning of the log

**Comment by anngdinh** [comment]
image

**Comment by def** [comment]
As you can see in the log, the agent tried to access the cri-o socket through: `/proc/1/root/var/run/crio/crio.sock` but encountered the `no such file or directory` error. This issue may arise if `/var/run/crio/crio.sock` or `/var/run/crio` is a symlink. Could you please check this?

**Comment by anngdinh** [comment]
No. It's not a symlink, it's a sock file. But i don't understand why node agent can read the file if I don't mount it.

**Comment by def** [comment]
The agent runs in the host PID namespace and has access to the proc filesystem. It can reach the host mount namespace through /proc/1/root/...

**Comment by anngdinh** [comment]
I see `/proc/1/root -> /`. I don't really catch it.
image

**Comment by def** [comment]
To understand this, please read the section explaining `/proc/pid/root` in this [documentation](https://man7.org/linux/man-pages/man5/proc.5.html)

**Pull request closed without merging**
